import { Metadata } from 'next'
import { ReactNode } from 'react'
import '@/styles/global.scss'
import ProviderLayout from './provider'
import Headers from '@/components/Headers/Headers'

export const metadata: Metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
}

const RootLayout = ({ children }: { children: ReactNode }) => {
	return (
		<ProviderLayout>
			<html lang='en'>
				<body>
					<Headers />
					{children}
				</body>
			</html>
		</ProviderLayout>
	)
}

export default RootLayout
